---
- name: Install git
  yum:
    name: git
    state: present

- name: Set git user.email
  git_config:
    name: user.email
    scope: global
    value: "{{ role_git_configure_user_email }}"

- name: Set git user.name
  git_config:
    name: user.name
    scope: global
    value: "{{ role_git_configure_user_name }}"

