---
- name: install python tools
  yum: name={{ item }} state=present
  with_items:
  - python2-pip
  - python-virtualenv

- name: update python tools
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
  - pip
  - setuptools

- name: install ansible-container
  pip:
    name: ansible-container
    state: present


