---
- hosts: "{{ config_groups | default('development-core') }}"
  become: yes
  roles:
    - vim-install
    - tmux-install
    - yum-update
    - xfce-install

- hosts: "{{ config_groups | default('development-core') }}"
  roles:
    - vim-yml
    - vim-configure
    - tmux-configure
    - get-disk-space

