---
- hosts: "{{ config_groups | default('development-email') }}"
  roles:
    #- role: debug-print-all
    - role: make-install

    - role: neomutt-install
      role_neomutt_install_clone_external_dir: "{{ config_clone_external_dir }}"
      role_neomutt_install_make_install_dir: "{{ config_make_install_dir }}"
      role_neomutt_install_version: "{{ config_neomutt_version }}"





